[package]
name = "Impulsor-3000"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
image = "0.24.8"
pdfium-render =  { version="0.8.17" }
rfd = "0.14"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
