name: Build Linux x64 LAME

on:
  workflow_dispatch:
  push:

jobs:
  build-libmp3lame-so:
    runs-on: ubuntu-24.04

    steps:
      - name: Install LAME
        run: |
          sudo apt update
          sudo apt install -y libmp3lame-dev

      - name: Collect shared libraries
        run: |
          LIB_DIR="/usr/lib/$(dpkg-architecture -qDEB_HOST_MULTIARCH)"
          mkdir -p output
          cp -L "${LIB_DIR}/libmp3lame.so" output/libmp3lame.so
          file output/libmp3lame.so
          readelf -d output/libmp3lame.so | grep -E 'SONAME|NEEDED'

      - name: Upload shared library artifact
        uses: actions/upload-artifact@v6
        with:
          name: libmp3lame-linux-x64
          path: output/
