name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  do-rust-stuff:
    uses: ./.github/workflows/rust.yml
  do-release:
    needs: do-rust-stuff
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: installer-windows
          path: ./installer
      - uses: actions/download-artifact@v5
        with:
          name: appimage-linux
          path: ./appimage
      - uses: actions/download-artifact@v5
        with:
          name: app-macos-arm64
          path: ./macos
      - uses: ncipollo/release-action@v1.20.0
        with:
          artifacts: "./installer/impulsor3000_setup.exe,./appimage/Impulsor-3000_x86-64.AppImage,./macos/Impulsor-3000.app"
          bodyFile: ""
